version: '3'
services:
  backend:
    build: .
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - goodies-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - goodies-network

networks:
  goodies-network:
    driver: bridge